name: unittest

on:
  push:
    branches:
     - '**'
  pull_request:
    branches: 
     - main
     - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up CUnit
      run: sudo apt-get install -y libcunit1-dev

    - name: Build project
      run: |
        make

    - name: Run tests
      run: |
        make test